In [48]:
primes=tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
print ("primes: ", primes)
print ("primes: ", primes.eval())
print('')
ones = tf.ones([6], dtype=tf.int32)
print ("ones : ", ones)
print ("ones : ", ones.eval())
print('\n')
just_beyond_primes = tf.add(primes, ones)
print ("just_beyond_primes:", just_beyond_primes)
print ("just_beyond_primes:", just_beyond_primes.eval())
print('')
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = primes * twos
print ("primes_doubled:", primes_doubled)
print ("primes_doubled:", primes_doubled.eval())

primes:  Tensor("Const_38:0", shape=(6,), dtype=int32)
primes:  [ 2  3  5  7 11 13]

ones :  Tensor("ones_17:0", shape=(6,), dtype=int32)
ones :  [1 1 1 1 1 1]


just_beyond_primes: Tensor("Add_15:0", shape=(6,), dtype=int32)
just_beyond_primes: [ 3  4  6  8 12 14]

primes_doubled: Tensor("mul_14:0", shape=(6,), dtype=int32)
primes_doubled: [ 4  6 10 14 22 26]


In [26]:
sess = tf.InteractiveSession()
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(type(some_matrix.eval()))
print ("\nvalue of some_matrix is:\n", some_matrix.eval())

<class 'numpy.ndarray'>

value of some_matrix is:
 [[1 2 3]
 [4 5 6]]


In [27]:
some_matrix.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [33]:
print(some_matrix.graph)

In [35]:
# A scalar (0-D tensor).
scalar = tf.zeros([])

# A vector with 3 elements.
vector = tf.zeros([3])

# A matrix with 2 rows and 3 columns.
matrix = tf.zeros([2, 3])

print ('scalar has shape', scalar.get_shape(), 'and value:\n', scalar.eval())
print ('vector has shape', vector.get_shape(), 'and value:\n', vector.eval())
print ('matrix has shape', matrix.get_shape(), 'and value:\n', matrix.eval())

scalar has shape () and value:
 0.0
vector has shape (3,) and value:
 [0. 0. 0.]
matrix has shape (2, 3) and value:
 [[0. 0. 0.]
 [0. 0. 0.]]


Broadcasting
In mathematics, you can only perform element-wise operations (e.g. add and equals) on tensors of the same shape. In TensorFlow, however, you may perform operations on tensors that would traditionally have been incompatible. TensorFlow supports broadcasting (a concept borrowed from numpy), where the smaller array in an element-wise operation is enlarged to have the same shape as the larger array.

NOTE: When a tensor is broadcast, its entries are conceptually copied. (They are not actually copied for performance reasons. Broadcasting was invented as a performance optimization.)
The full broadcasting ruleset is well described in the easy-to-read numpy broadcasting documentation.
The following code performs the same tensor arithmetic as before, but instead uses scalar values (instead of vectors containing all 1s or all 2s) and broadcasting.

In [50]:
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
print ("primes:", primes)
print ("primes:", primes.eval())
print('')
one = tf.constant(1, dtype=tf.int32)
print ("one:", one)
print ("ones : ", ones.eval())
print('')

just_beyond_primes = tf.add(primes, one)
print ("just_beyond_primes:", just_beyond_primes)
print ("just_beyond_primes:", just_beyond_primes.eval())
print('')
two = tf.constant(2, dtype=tf.int32)
primes_doubled = primes * two
print ("primes_doubled:", primes_doubled)
print ("primes_doubled:", primes_doubled.eval())


primes: Tensor("Const_40:0", shape=(6,), dtype=int32)
primes: [ 2  3  5  7 11 13]

one: Tensor("Const_41:0", shape=(), dtype=int32)
ones :  [1 1 1 1 1 1]

just_beyond_primes: Tensor("Add_16:0", shape=(6,), dtype=int32)
just_beyond_primes: [ 3  4  6  8 12 14]

primes_doubled: Tensor("mul_15:0", shape=(6,), dtype=int32)
primes_doubled: [ 4  6 10 14 22 26]


Exercise #1: Arithmetic over vectors.
Perform vector arithmetic to create a "just_under_primes_squared" vector, where the ith element is equal to the ith element in primes squared, minus 1. For example, the second element would be equal to 3 * 3 - 1 = 8.
Make use of either the tf.multiply or tf.pow ops to square the value of each element in the primes vector.

In [52]:
primes_squared=tf.pow(primes,2)
just_under_primes_squared=tf.subtract(primes_squared,one)
print ("just_under_primes_squared: ", just_under_primes_squared)
print ("just_under_primes_squared: ", just_under_primes_squared.eval())

just_under_primes_squared:  Tensor("Sub:0", shape=(6,), dtype=int32)
just_under_primes_squared:  [  3   8  24  48 120 168]


In [65]:
# A 3x4 matrix (2-d tensor).
x = tf.constant([[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]],
                dtype=tf.int32)
print("x: ", x.eval())
print('')
# A 4x2 matrix (2-d tensor).
y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)
print ("y: ", y.eval())
# Multiply `x` by `y`; result is 3x2 matrix.
matrix_multiply_result = tf.matmul(x, y)

print ('matrix_multiply_result: ',matrix_multiply_result.eval())

x:  [[ 5  2  4  3]
 [ 5  1  6 -2]
 [-1  3 -1 -2]]

y:  [[2 2]
 [3 5]
 [4 5]
 [1 6]]
matrix_multiply_result:  [[35 58]
 [35 33]
 [ 1 -4]]


Tensor Reshaping
With tensor addition and matrix multiplication each imposing constraints on operands, TensorFlow programmers must frequently reshape tensors.
You can use the tf.reshape method to reshape a tensor. For example, you can reshape a 8x2 tensor into a 2x8 tensor or a 4x4 tensor:

In [68]:
# Create an 8x2 matrix (2-D tensor).
matrix = tf.constant(
    [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]],
    dtype=tf.int32)

reshaped_2x8_matrix = tf.reshape(matrix, [2, 8])
reshaped_4x4_matrix = tf.reshape(matrix, [4, 4])

print ("Original matrix (8x2):")
print (matrix.eval())
print ("Reshaped matrix (2x8):")
print (reshaped_2x8_matrix.eval())
print ("Reshaped matrix (4x4):")
print (reshaped_4x4_matrix.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped matrix (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


You can also use tf.reshape to change the number of dimensions (the "rank") of the tensor. For example, you could reshape that 8x2 tensor into a 3-D 2x2x4 tensor or a 1-D 16-element tensor.

In [69]:
# Create an 8x2 matrix (2-D tensor).
matrix = tf.constant(
    [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]],
    dtype=tf.int32)

reshaped_2x2x4_tensor = tf.reshape(matrix, [2, 2, 4])
one_dimensional_vector = tf.reshape(matrix, [16])

print ("Original matrix (8x2):")
print (matrix.eval())
print ("Reshaped matrix (2x2x4):")
print (reshaped_2x2x4_tensor.eval())
print ("Reshaped matrix (4x4):")
print (one_dimensional_vector.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x2x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Reshaped matrix (4x4):
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


Exercise #2: Reshape two tensors in order to multiply them.
The following two vectors are incompatible for matrix multiplication:
a = tf.constant([5, 3, 2, 7, 1, 4])
b = tf.constant([4, 6, 3])
Reshape these vectors into compatible operands for matrix multiplication. Then, invoke a matrix multiplication operation on the reshaped tensors.

In [81]:
a = tf.constant([5, 3, 2, 7, 1, 4]) 
b = tf.constant([4, 6, 3])
reshaped_a=tf.reshape(a,[2,3])
reshaped_b=tf.reshape(b,[3,1])
print(reshaped_a)
print (reshaped_a.eval())
print (reshaped_b)
print (reshaped_b.eval())

Tensor("Reshape_17:0", shape=(2, 3), dtype=int32)
[[5 3 2]
 [7 1 4]]
Tensor("Reshape_18:0", shape=(3, 1), dtype=int32)
[[4]
 [6]
 [3]]


In [77]:
multiply_reshaped_ab=tf.matmul(reshaped_a,reshaped_b)

In [78]:
print(multiply_reshaped_ab)

Tensor("MatMul_4:0", shape=(2, 1), dtype=int32)


In [82]:
print(multiply_reshaped_ab.eval())

[[44]
 [46]]


Variables, Initialization and Assignment:
So far, all the operations we performed were on static values (tf.constant); calling numpy() always returned the same result. TensorFlow allows you to define Variable objects, whose values can be changed.
When creating a variable, you can set an initial value explicitly, or you can use an initializer (like a distribution):

In [105]:
# Create a scalar variable with the initial value 3.

# Create a vector variable of shape [1, 4], with random initial values,
# sampled from a normal distribution with mean 1 and standard deviation 0.35.
w =tf.get_variable("w", dtype=tf.float32,
  initializer=tf.random_normal([1, 4], mean=1.0, stddev=0.35))

In [107]:
print(sess.run(tf.report_uninitialized_variables()))

[b'Variable' b'Variable_1' b'Variable_2' b'Variable_3' b'Variable_4'
 b'Variable_5' b'Variable_6' b'Variable_7' b'Variable_8' b'Variable_9'
 b'v' b'w']


In [109]:
sess.run(tf.global_variables_initializer())
# Now all variables are initialized.

In [110]:
print(sess.run(tf.report_uninitialized_variables()))

[]


In [111]:
print(v.eval())

[-0.09638667  0.9776943   0.4332099 ]


In [125]:
print (w.eval())
print(v)

[[0.75196075 0.66704667 1.2290208  0.7418922 ]]


In [127]:
print(w.eval())

[[0.75196075 0.66704667 1.2290208  0.7418922 ]]


In [130]:
tf.variable_scope("v", reuse=True)

In [138]:
v1 =tf.get_variable("v1", dtype=tf.int32,
      initializer=([3]))

In [140]:
print(sess.run(tf.report_uninitialized_variables()))

[b'v1']


In [141]:
sess.run(tf.global_variables_initializer())
# Now all variables are initialized.

In [142]:
print(sess.run(tf.report_uninitialized_variables()))

[]


In [144]:
print (v1.eval())

[3]


In [153]:
tf.assign(v1,[7])
assignment=v1.assign([5])
tf.global_variables_initializer().run()

In [156]:
assignment.eval()
print(v1.eval())

[5]


In [157]:
assignment=v1.assign_add([7])

In [158]:
assignment.eval()
print(v1.eval())

[12]


Exercise #3: Simulate 10 rolls of two dice.
Create a dice simulation, which generates a 10x3 2-D tensor in which:
Columns 1 and 2 each hold one throw of one six-sided die (with values 1–6).
Column 3 holds the sum of Columns 1 and 2 on the same row.
For example, the first row might have the following values:
Column 1 holds 4
Column 2 holds 3
Column 3 holds 7

In [160]:
die1 =tf.get_variable("die1",
  initializer=tf.random_uniform(minval=1,shape=[10,1],maxval=7,dtype=tf.int32))
die2 =tf.get_variable("die2",
  initializer=tf.random_uniform(minval=1,shape=[10,1],maxval=7,dtype=tf.int32))

In [161]:
print(sess.run(tf.report_uninitialized_variables()))

[b'die1' b'die2']


In [163]:
die_sum=tf.add(die1,die2)

In [165]:
result=tf.concat(values=[die1,die2,die_sum],axis=1)

In [166]:
tf.global_variables_initializer().run()

In [167]:
print(sess.run(tf.report_uninitialized_variables()))

[]


In [170]:
print("Resulting Matrix simulating 10 rolls of 2 dice of shape 10x3: ")
print(result.eval())

Resulting Matrix simulating 10 rolls of 2 dice of shape 10x3: 
[[ 1  3  4]
 [ 4  6 10]
 [ 1  1  2]
 [ 6  3  9]
 [ 2  5  7]
 [ 4  4  8]
 [ 4  3  7]
 [ 5  6 11]
 [ 2  2  4]
 [ 2  6  8]]
